// Membership and most example words/readings checked against Langoal on 2026-10-08.
// Numbered topic groups are combined. English glosses are shortened/corrected.
// The source page for 末 lists 未 examples; 週末 is verified against the Japan Foundation.
export const n3 = {
  id: 'n3',
  label: 'JLPT N3',
  source: 'https://langoal.com/teaching-materials/kanji/n3-overview.html',
  verifiedOn: '2026-10-08',
  cards: [
    {"kanji": "曜", "word": "曜日", "reading": "ようび", "meaning": "day of the week", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/you-weekday"},
    {"kanji": "末", "word": "週末", "reading": "しゅうまつ", "meaning": "weekend", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/mi-not-yet", "vocabularySource": "https://www.jpf.or.kr/irodori/sData/pdf/resources/wordlist_X.pdf"},
    {"kanji": "昨", "word": "昨日", "reading": "きのう", "meaning": "yesterday", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/kinou-yesterday"},
    {"kanji": "翌", "word": "翌日", "reading": "よくじつ", "meaning": "next day", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/yoku-next"},
    {"kanji": "現", "word": "現在", "reading": "げんざい", "meaning": "present; now", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/arawasu-show"},
    {"kanji": "昔", "word": "昔", "reading": "むかし", "meaning": "old days", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/mukashi-old-days"},
    {"kanji": "次", "word": "次", "reading": "つぎ", "meaning": "next", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/tsugi-next"},
    {"kanji": "回", "word": "今回", "reading": "こんかい", "meaning": "this time", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/mawaru-turn"},
    {"kanji": "再", "word": "再び", "reading": "ふたたび", "meaning": "again", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/futatabi-again"},
    {"kanji": "旧", "word": "旧友", "reading": "きゅうゆう", "meaning": "old friend", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/kyuu-old-times"},
    {"kanji": "秒", "word": "秒", "reading": "びょう", "meaning": "second", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/byou-second"},
    {"kanji": "彼", "word": "彼", "reading": "かれ", "meaning": "he; boyfriend", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/kare-he"},
    {"kanji": "君", "word": "君", "reading": "きみ", "meaning": "you (informal)", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/kimi-you"},
    {"kanji": "仲", "word": "仲", "reading": "なか", "meaning": "relationship", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/naka-relationship"},
    {"kanji": "達", "word": "友達", "reading": "ともだち", "meaning": "friend", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/tachi-accomplished"},
    {"kanji": "供", "word": "子供", "reading": "こども", "meaning": "child", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/tomo-accompany"},
    {"kanji": "娘", "word": "娘", "reading": "むすめ", "meaning": "daughter", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/musume-daughter"},
    {"kanji": "婦", "word": "主婦", "reading": "しゅふ", "meaning": "housewife", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/fu-woman"},
    {"kanji": "老", "word": "老人", "reading": "ろうじん", "meaning": "old person", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/rou-old"},
    {"kanji": "他", "word": "他", "reading": "ほか", "meaning": "other", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/hoka-other"},
    {"kanji": "頭", "word": "頭", "reading": "あたま", "meaning": "head", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/atama-head"},
    {"kanji": "顔", "word": "顔", "reading": "かお", "meaning": "face", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/kao-face"},
    {"kanji": "鼻", "word": "鼻", "reading": "はな", "meaning": "nose", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/hana-nose"},
    {"kanji": "首", "word": "首", "reading": "くび", "meaning": "neck", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/kubi-neck"},
    {"kanji": "血", "word": "血", "reading": "ち", "meaning": "blood", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/chi-blood"},
    {"kanji": "液", "word": "液体", "reading": "えきたい", "meaning": "fluid", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/eki-liquid"},
    {"kanji": "歯", "word": "歯", "reading": "は", "meaning": "tooth", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/ha-tooth"},
    {"kanji": "型", "word": "型", "reading": "かた", "meaning": "mold", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/kata-type"},
    {"kanji": "氷", "word": "氷", "reading": "こおり", "meaning": "ice", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/koori-ice"},
    {"kanji": "湯", "word": "湯", "reading": "ゆ", "meaning": "hot water", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/yu-hot-water"},
    {"kanji": "卵", "word": "卵", "reading": "たまご", "meaning": "egg", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/tamago-egg"},
    {"kanji": "豆", "word": "豆", "reading": "まめ", "meaning": "beans", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/mame-beans"},
    {"kanji": "粉", "word": "粉", "reading": "こな", "meaning": "powder; flour", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/kona-flour"},
    {"kanji": "乳", "word": "牛乳", "reading": "ぎゅうにゅう", "meaning": "milk", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/nyuu-milk"},
    {"kanji": "塩", "word": "塩", "reading": "しお", "meaning": "salt", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/shio-salt"},
    {"kanji": "調", "word": "調味料", "reading": "ちょうみりょう", "meaning": "seasoning", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/shiraberu-investigate"},
    {"kanji": "和", "word": "和食", "reading": "わしょく", "meaning": "Japanese food", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/wa-japan"},
    {"kanji": "熱", "word": "熱い", "reading": "あつい", "meaning": "hot to the touch", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/netsu-heat"},
    {"kanji": "冷", "word": "冷たい", "reading": "つめたい", "meaning": "cold to the touch", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/tsumetai-cool"},
    {"kanji": "暖", "word": "暖かい", "reading": "あたたかい", "meaning": "warm (weather)", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/atatakai-warm"},
    {"kanji": "温", "word": "温かい", "reading": "あたたかい", "meaning": "warm (to the touch)", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/on-temperature"},
    {"kanji": "良", "word": "良い", "reading": "いい", "meaning": "good", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/ii-good"},
    {"kanji": "悪", "word": "悪い", "reading": "わるい", "meaning": "bad", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/warui-bad"},
    {"kanji": "厚", "word": "厚い", "reading": "あつい", "meaning": "thick", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/atsui-thick"},
    {"kanji": "易", "word": "易しい", "reading": "やさしい", "meaning": "easy", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/yasashii-easy"},
    {"kanji": "難", "word": "難しい", "reading": "むずかしい", "meaning": "difficult", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/muzukashii-difficult"},
    {"kanji": "深", "word": "深い", "reading": "ふかい", "meaning": "deep", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/fukai-deep"},
    {"kanji": "浅", "word": "浅い", "reading": "あさい", "meaning": "shallow", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/asai-shallow"},
    {"kanji": "痛", "word": "痛い", "reading": "いたい", "meaning": "painful", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/itai-pain"},
    {"kanji": "苦", "word": "苦しい", "reading": "くるしい", "meaning": "painful; difficult", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/kurushii-suffering"},
    {"kanji": "欲", "word": "欲しい", "reading": "ほしい", "meaning": "want", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/hoshii-want"},
    {"kanji": "捨", "word": "捨てる", "reading": "すてる", "meaning": "throw away", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/suteru-throw-away"},
    {"kanji": "拾", "word": "拾う", "reading": "ひろう", "meaning": "pick up", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/hirou-pick-up"},
    {"kanji": "貸", "word": "貸す", "reading": "かす", "meaning": "lend", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kasu-lend"},
    {"kanji": "借", "word": "借りる", "reading": "かりる", "meaning": "borrow", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kariru-borrow"},
    {"kanji": "覚", "word": "覚える", "reading": "おぼえる", "meaning": "remember", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/oboeru-remember"},
    {"kanji": "忘", "word": "忘れる", "reading": "わすれる", "meaning": "forget", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/wasureru-forget"},
    {"kanji": "押", "word": "押す", "reading": "おす", "meaning": "push", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/osu-push"},
    {"kanji": "引", "word": "引く", "reading": "ひく", "meaning": "pull", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/hiku-pull"},
    {"kanji": "打", "word": "打つ", "reading": "うつ", "meaning": "hit", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/utsu-hit"},
    {"kanji": "投", "word": "投げる", "reading": "なげる", "meaning": "throw", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/nageru-throw"},
    {"kanji": "信", "word": "信じる", "reading": "しんじる", "meaning": "believe", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/shinjiru-believe"},
    {"kanji": "伝", "word": "伝える", "reading": "つたえる", "meaning": "convey; tell", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/tsutaeru-report"},
    {"kanji": "想", "word": "想像", "reading": "そうぞう", "meaning": "imagination", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/omou-thought"},
    {"kanji": "続", "word": "続ける", "reading": "つづける", "meaning": "continue", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/tsuzuku-continue"},
    {"kanji": "祝", "word": "祝う", "reading": "いわう", "meaning": "celebrate", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/iwau-celebrate"},
    {"kanji": "願", "word": "願う", "reading": "ねがう", "meaning": "wish", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/negau-wish"},
    {"kanji": "酔", "word": "酔う", "reading": "よう", "meaning": "get drunk", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/you-drunk"},
    {"kanji": "起", "word": "起きる", "reading": "おきる", "meaning": "get up", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/okiru-wakeup"},
    {"kanji": "寝", "word": "寝る", "reading": "ねる", "meaning": "go to bed", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/neru-sleep"},
    {"kanji": "洗", "word": "洗う", "reading": "あらう", "meaning": "wash", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/arau-wash"},
    {"kanji": "濯", "word": "洗濯", "reading": "せんたく", "meaning": "laundry", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/susugu-rinse"},
    {"kanji": "干", "word": "干す", "reading": "ほす", "meaning": "dry", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/hosu-dry"},
    {"kanji": "浴", "word": "浴びる", "reading": "あびる", "meaning": "bathe", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/abiru-bathe"},
    {"kanji": "活", "word": "生活", "reading": "せいかつ", "meaning": "life", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/katsu-lively"},
    {"kanji": "夢", "word": "夢", "reading": "ゆめ", "meaning": "dream", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/yume-dream"},
    {"kanji": "貯", "word": "貯める", "reading": "ためる", "meaning": "save", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/tameru-save"},
    {"kanji": "列", "word": "列", "reading": "れつ", "meaning": "queue", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/retsu-queue"},
    {"kanji": "袋", "word": "袋", "reading": "ふくろ", "meaning": "bag", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/fukuro-bag"},
    {"kanji": "久", "word": "久しぶり", "reading": "ひさしぶり", "meaning": "after a long time", "category": "Daily life", "source": "https://langoal.com/teaching-materials/kanji/hisashiburi-longtime"},
    {"kanji": "喜", "word": "喜ぶ", "reading": "よろこぶ", "meaning": "be delighted", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/yorokobu-delight"},
    {"kanji": "怒", "word": "怒る", "reading": "おこる", "meaning": "get angry", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/okoru-angry"},
    {"kanji": "笑", "word": "笑う", "reading": "わらう", "meaning": "laugh", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/warau-laugh"},
    {"kanji": "泣", "word": "泣く", "reading": "なく", "meaning": "cry", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/naku-cry"},
    {"kanji": "悲", "word": "悲しい", "reading": "かなしい", "meaning": "sad", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/kanashii-sad"},
    {"kanji": "涙", "word": "涙", "reading": "なみだ", "meaning": "tear", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/namida-tear"},
    {"kanji": "幸", "word": "幸せ", "reading": "しあわせ", "meaning": "happiness", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/shiawase-happiness"},
    {"kanji": "感", "word": "感じる", "reading": "かんじる", "meaning": "feel", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/kanji-feeling"},
    {"kanji": "情", "word": "感情", "reading": "かんじょう", "meaning": "emotion", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/nasake-sympathy"},
    {"kanji": "悩", "word": "悩む", "reading": "なやむ", "meaning": "be worried", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/nayamu-worry"},
    {"kanji": "困", "word": "困る", "reading": "こまる", "meaning": "be in trouble", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/komaru-beintrouble"},
    {"kanji": "残", "word": "残る", "reading": "のこる", "meaning": "remain", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/nokoru-remain"},
    {"kanji": "念", "word": "残念", "reading": "ざんねん", "meaning": "disappointing", "category": "Feelings", "source": "https://langoal.com/teaching-materials/kanji/nen-feeling"},
    {"kanji": "関", "word": "関わる", "reading": "かかわる", "meaning": "be involved", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/kakawaru-beinvolved"},
    {"kanji": "係", "word": "係", "reading": "かかり", "meaning": "person in charge", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/kakari-personincharge"},
    {"kanji": "結", "word": "結ぶ", "reading": "むすぶ", "meaning": "tie", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/musubu-tie"},
    {"kanji": "婚", "word": "結婚", "reading": "けっこん", "meaning": "marriage", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/kon-marriage"},
    {"kanji": "独", "word": "独り", "reading": "ひとり", "meaning": "alone", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/hitori-alone"},
    {"kanji": "身", "word": "独身", "reading": "どくしん", "meaning": "unmarried", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/mi-body"},
    {"kanji": "恋", "word": "恋", "reading": "こい", "meaning": "love", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/koi-romance"},
    {"kanji": "愛", "word": "愛", "reading": "あい", "meaning": "love", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/ai-love"},
    {"kanji": "永", "word": "永遠", "reading": "えいえん", "meaning": "eternity", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/nagai-eternity"},
    {"kanji": "福", "word": "福", "reading": "ふく", "meaning": "good fortune", "category": "Relationships", "source": "https://langoal.com/teaching-materials/kanji/fuku-luck"},
    {"kanji": "予", "word": "天気予報", "reading": "てんきよほう", "meaning": "weather forecast", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/arakajime-beforehand"},
    {"kanji": "定", "word": "予定", "reading": "よてい", "meaning": "plan; schedule", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/sadameru-decide"},
    {"kanji": "用", "word": "用意", "reading": "ようい", "meaning": "preparation", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/mochiiru-use"},
    {"kanji": "事", "word": "用事", "reading": "ようじ", "meaning": "errand", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/koto-thing"},
    {"kanji": "約", "word": "約束", "reading": "やくそく", "meaning": "promise", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/yaku-promise"},
    {"kanji": "束", "word": "花束", "reading": "はなたば", "meaning": "bouquet", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/taba-bundle"},
    {"kanji": "必", "word": "必ず", "reading": "かならず", "meaning": "certainly", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/kanarazu-certainly"},
    {"kanji": "要", "word": "要る", "reading": "いる", "meaning": "need", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/iru-need"},
    {"kanji": "取", "word": "取る", "reading": "とる", "meaning": "take something", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/toru-take"},
    {"kanji": "消", "word": "消す", "reading": "けす", "meaning": "erase", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/kesu-extinguish"},
    {"kanji": "返", "word": "返す", "reading": "かえす", "meaning": "return (something)", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/kaesu-return"},
    {"kanji": "守", "word": "守る", "reading": "まもる", "meaning": "protect", "category": "Plans", "source": "https://langoal.com/teaching-materials/kanji/mamoru-protect"},
    {"kanji": "杯", "word": "一杯", "reading": "いっぱい", "meaning": "one cup", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/sakazuki-glass"},
    {"kanji": "枚", "word": "枚", "reading": "まい", "meaning": "counter for flat objects", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/mai-sheet-of"},
    {"kanji": "匹", "word": "匹", "reading": "ひき", "meaning": "small animal counter", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/hiki-counter-small-animal"},
    {"kanji": "冊", "word": "冊", "reading": "さつ", "meaning": "counter for books", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/satsu-counter-book"},
    {"kanji": "各", "word": "各自", "reading": "かくじ", "meaning": "individual", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/kaku-each"},
    {"kanji": "量", "word": "量", "reading": "りょう", "meaning": "quantity", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/ryou-quantity"},
    {"kanji": "最", "word": "最も", "reading": "もっとも", "meaning": "most", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/mottomo-most"},
    {"kanji": "単", "word": "簡単", "reading": "かんたん", "meaning": "easy", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/tan-one"},
    {"kanji": "複", "word": "複雑", "reading": "ふくざつ", "meaning": "complicated", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/fuku-multiple"},
    {"kanji": "全", "word": "全て", "reading": "すべて", "meaning": "all", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/subete-all"},
    {"kanji": "以", "word": "以上", "reading": "いじょう", "meaning": "at least; or more", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/i-compared"},
    {"kanji": "未", "word": "未来", "reading": "みらい", "meaning": "future", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/imada-not-yet"},
    {"kanji": "満", "word": "未満", "reading": "みまん", "meaning": "less than", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/michiru-full"},
    {"kanji": "無", "word": "無い", "reading": "ない", "meaning": "not exist; not have", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/mu-nothing"},
    {"kanji": "非", "word": "非常口", "reading": "ひじょうぐち", "meaning": "emergency exit", "category": "Quantities", "source": "https://langoal.com/teaching-materials/kanji/hi-mistake"},
    {"kanji": "季", "word": "季節", "reading": "きせつ", "meaning": "season", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/ki-season"},
    {"kanji": "候", "word": "気候", "reading": "きこう", "meaning": "climate", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/kou-climate"},
    {"kanji": "島", "word": "島", "reading": "しま", "meaning": "island", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/shima-island"},
    {"kanji": "陸", "word": "陸", "reading": "りく", "meaning": "land", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/riku-land"},
    {"kanji": "河", "word": "河", "reading": "かわ", "meaning": "river (especially a large river)", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/kawa-big-river"},
    {"kanji": "流", "word": "流れる", "reading": "ながれる", "meaning": "flow", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/nagareru-stream"},
    {"kanji": "陽", "word": "太陽", "reading": "たいよう", "meaning": "sun", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/you-sunshine"},
    {"kanji": "岸", "word": "岸", "reading": "きし", "meaning": "shore", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/kishi-coast"},
    {"kanji": "農", "word": "農業", "reading": "のうぎょう", "meaning": "agriculture", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/nou-agriculture"},
    {"kanji": "産", "word": "産む", "reading": "うむ", "meaning": "give birth", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/umu-produce"},
    {"kanji": "果", "word": "果物", "reading": "くだもの", "meaning": "fruit", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/ka-fruit"},
    {"kanji": "実", "word": "果実", "reading": "かじつ", "meaning": "fruit", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/mi-fruit"},
    {"kanji": "葉", "word": "葉", "reading": "は", "meaning": "leaf", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/ha-leaf"},
    {"kanji": "菜", "word": "野菜", "reading": "やさい", "meaning": "vegetable", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/na-vegetable"},
    {"kanji": "植", "word": "植える", "reading": "うえる", "meaning": "plant", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/ueru-plant"},
    {"kanji": "根", "word": "根", "reading": "ね", "meaning": "root", "category": "Agriculture", "source": "https://langoal.com/teaching-materials/kanji/ne-root"},
    {"kanji": "位", "word": "位置", "reading": "いち", "meaning": "position", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/kurai-rank"},
    {"kanji": "置", "word": "置く", "reading": "おく", "meaning": "put", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/oku-put"},
    {"kanji": "存", "word": "存在", "reading": "そんざい", "meaning": "existence", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/son-being"},
    {"kanji": "在", "word": "在宅", "reading": "ざいたく", "meaning": "being at home", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/zai-exist"},
    {"kanji": "積", "word": "積む", "reading": "つむ", "meaning": "pile up", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/tsumoru-pile-up"},
    {"kanji": "央", "word": "中央", "reading": "ちゅうおう", "meaning": "centre", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/ou-center"},
    {"kanji": "向", "word": "向かう", "reading": "むかう", "meaning": "head towards", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/mukau-facing"},
    {"kanji": "底", "word": "底", "reading": "そこ", "meaning": "bottom", "category": "Directions", "source": "https://langoal.com/teaching-materials/kanji/soko-bottom"},
    {"kanji": "建", "word": "建物", "reading": "たてもの", "meaning": "building", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/tateru-build"},
    {"kanji": "築", "word": "建築", "reading": "けんちく", "meaning": "architecture", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/kizuku-construct"},
    {"kanji": "構", "word": "構造", "reading": "こうぞう", "meaning": "structure", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/kamau-mind"},
    {"kanji": "造", "word": "造る", "reading": "つくる", "meaning": "create", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/tsukuru-create"},
    {"kanji": "設", "word": "建設", "reading": "けんせつ", "meaning": "construction", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/moukeru-establishment"},
    {"kanji": "橋", "word": "橋", "reading": "はし", "meaning": "bridge", "category": "Buildings", "source": "https://langoal.com/teaching-materials/kanji/hashi-bridge"},
    {"kanji": "窓", "word": "窓", "reading": "まど", "meaning": "window", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/mado-window"},
    {"kanji": "戸", "word": "戸", "reading": "と", "meaning": "Japanese-style door", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/to-gate"},
    {"kanji": "階", "word": "階段", "reading": "かいだん", "meaning": "stairs", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/kai-stair"},
    {"kanji": "段", "word": "段階", "reading": "だんかい", "meaning": "stage", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/dan-stair"},
    {"kanji": "机", "word": "机", "reading": "つくえ", "meaning": "desk", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/tsukue-desk"},
    {"kanji": "柱", "word": "柱", "reading": "はしら", "meaning": "pillar", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/hashira-pillar"},
    {"kanji": "庫", "word": "冷蔵庫", "reading": "れいぞうこ", "meaning": "refrigerator", "category": "Home", "source": "https://langoal.com/teaching-materials/kanji/ko-warehouse"},
    {"kanji": "角", "word": "角", "reading": "かど", "meaning": "corner", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/kado-corner"},
    {"kanji": "坂", "word": "坂", "reading": "さか", "meaning": "slope", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/saka-slope"},
    {"kanji": "折", "word": "折る", "reading": "おる", "meaning": "fold; break", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/oru-fold"},
    {"kanji": "曲", "word": "曲がる", "reading": "まがる", "meaning": "turn; bend", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/magaru-turn"},
    {"kanji": "路", "word": "道路", "reading": "どうろ", "meaning": "road", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/ro-road"},
    {"kanji": "側", "word": "向こう側", "reading": "むこうがわ", "meaning": "other side", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/gawa-side"},
    {"kanji": "直", "word": "直す", "reading": "なおす", "meaning": "fix", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/naosu-fix"},
    {"kanji": "線", "word": "線", "reading": "せん", "meaning": "line", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/sen-line"},
    {"kanji": "逆", "word": "逆", "reading": "ぎゃく", "meaning": "reverse", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/gyaku-opposite"},
    {"kanji": "進", "word": "進む", "reading": "すすむ", "meaning": "advance", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/susumu-progress"},
    {"kanji": "禁", "word": "禁止", "reading": "きんし", "meaning": "prohibition", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/kin-prohibition"},
    {"kanji": "許", "word": "許可", "reading": "きょか", "meaning": "permission", "category": "Driving", "source": "https://langoal.com/teaching-materials/kanji/yurusu-permit"},
    {"kanji": "初", "word": "初めて", "reading": "はじめて", "meaning": "for the first time", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/hatsu-first"},
    {"kanji": "姓", "word": "姓", "reading": "せい", "meaning": "surname", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/sei-surname"},
    {"kanji": "個", "word": "個人", "reading": "こじん", "meaning": "individual", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/ko-individual"},
    {"kanji": "性", "word": "女性", "reading": "じょせい", "meaning": "woman", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/sei-gender"},
    {"kanji": "変", "word": "変", "reading": "へん", "meaning": "strange", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/kaeru-change"},
    {"kanji": "付", "word": "付く", "reading": "つく", "meaning": "be attached", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/tsukeru-attach"},
    {"kanji": "紹", "word": "紹介", "reading": "しょうかい", "meaning": "introduction", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/shou-introduce"},
    {"kanji": "介", "word": "自己紹介", "reading": "じこしょうかい", "meaning": "self-introduction", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/kai-mediate"},
    {"kanji": "常", "word": "常に", "reading": "つねに", "meaning": "always", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/tsune-always"},
    {"kanji": "識", "word": "常識", "reading": "じょうしき", "meaning": "common sense", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/shiki-acquaintanceship"},
    {"kanji": "失", "word": "失う", "reading": "うしなう", "meaning": "lose", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/ushinau-lose"},
    {"kanji": "礼", "word": "お礼", "reading": "おれい", "meaning": "thanks", "category": "Introductions", "source": "https://langoal.com/teaching-materials/kanji/rei-gratitude"},
    {"kanji": "授", "word": "授業", "reading": "じゅぎょう", "meaning": "lesson", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/sazukeru-give"},
    {"kanji": "業", "word": "産業", "reading": "さんぎょう", "meaning": "industry", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/gyou-business"},
    {"kanji": "欠", "word": "欠席", "reading": "けっせき", "meaning": "absence", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/kakeru-lack"},
    {"kanji": "席", "word": "席", "reading": "せき", "meaning": "seat", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/seki-seat"},
    {"kanji": "成", "word": "成功", "reading": "せいこう", "meaning": "success", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/naru-become"},
    {"kanji": "績", "word": "成績", "reading": "せいせき", "meaning": "grades", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/seki-achievement"},
  ],
};
