// Kanji membership and contextual words/readings checked against Langoal on 2026-10-08.
// English glosses are shortened and corrected where needed. One vocabulary example per kanji.
export const n4 = {
  id: 'n4',
  label: 'JLPT N4',
  source: 'https://langoal.com/teaching-materials/kanji/n4-overview.html',
  verifiedOn: '2026-10-08',
  cards: [
    {"kanji": "朝", "word": "朝", "reading": "あさ", "meaning": "morning", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/asa-morning"},
    {"kanji": "昼", "word": "昼", "reading": "ひる", "meaning": "noon", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/hiru-noon"},
    {"kanji": "晩", "word": "晩", "reading": "ばん", "meaning": "evening", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/ban-night"},
    {"kanji": "夜", "word": "夜", "reading": "よる", "meaning": "night", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/yoru-night"},
    {"kanji": "前", "word": "前", "reading": "まえ", "meaning": "front; before", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/mae-front"},
    {"kanji": "後", "word": "後ろ", "reading": "うしろ", "meaning": "behind", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/ushiro-behind"},
    {"kanji": "正", "word": "正しい", "reading": "ただしい", "meaning": "correct", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/tadashii"},
    {"kanji": "午", "word": "午前", "reading": "ごぜん", "meaning": "a.m.", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/go-horse"},
    {"kanji": "毎", "word": "毎日", "reading": "まいにち", "meaning": "every day", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/mai-every"},
    {"kanji": "週", "word": "今週", "reading": "こんしゅう", "meaning": "this week", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/shuu-week"},
    {"kanji": "去", "word": "去る", "reading": "さる", "meaning": "leave", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/saru-leave"},
    {"kanji": "家", "word": "家", "reading": "いえ", "meaning": "house", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/ie-house"},
    {"kanji": "族", "word": "家族", "reading": "かぞく", "meaning": "family", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/zoku-family"},
    {"kanji": "兄", "word": "兄", "reading": "あに", "meaning": "(my) older brother", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/ani-older-brother"},
    {"kanji": "弟", "word": "弟", "reading": "おとうと", "meaning": "(my) younger brother", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/otouto-younger-brother"},
    {"kanji": "姉", "word": "姉", "reading": "あね", "meaning": "older sister", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/ane-older-sister"},
    {"kanji": "妹", "word": "妹", "reading": "いもうと", "meaning": "younger sister", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/imouto-younger-sister"},
    {"kanji": "夫", "word": "夫", "reading": "おっと", "meaning": "husband", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/otto-husband"},
    {"kanji": "妻", "word": "妻", "reading": "つま", "meaning": "wife", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/tsuma-wife"},
    {"kanji": "主", "word": "主人", "reading": "しゅじん", "meaning": "husband", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/nushi-lord"},
    {"kanji": "奥", "word": "奥", "reading": "おく", "meaning": "inner part", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/oku-inner"},
    {"kanji": "私", "word": "私", "reading": "わたし", "meaning": "I; me", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/watashi-me"},
    {"kanji": "王", "word": "王", "reading": "おう", "meaning": "king", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/ousama"},
    {"kanji": "様", "word": "王様", "reading": "おうさま", "meaning": "king", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/sama-esq"},
    {"kanji": "才", "word": "六才", "reading": "ろくさい", "meaning": "6 years old", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/sai-age"},
    {"kanji": "赤", "word": "赤", "reading": "あか", "meaning": "red", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/aka"},
    {"kanji": "青", "word": "青", "reading": "あお", "meaning": "blue", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/ao"},
    {"kanji": "白", "word": "白", "reading": "しろ", "meaning": "white", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/shiro"},
    {"kanji": "黒", "word": "黒", "reading": "くろ", "meaning": "black", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/kuro-black"},
    {"kanji": "色", "word": "色", "reading": "いろ", "meaning": "color", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/iro-color"},
    {"kanji": "銀", "word": "銀", "reading": "ぎん", "meaning": "silver", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/gin-silver"},
    {"kanji": "黄", "word": "黄色", "reading": "きいろ", "meaning": "yellow", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/ki-yellow"},
    {"kanji": "緑", "word": "緑", "reading": "みどり", "meaning": "green", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/midori-green"},
    {"kanji": "丸", "word": "丸", "reading": "まる", "meaning": "round", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/maru-round"},
    {"kanji": "玉", "word": "玉", "reading": "たま", "meaning": "ball", "category": "Colours & shapes", "source": "https://langoal.com/teaching-materials/kanji/tama"},
    {"kanji": "春", "word": "春", "reading": "はる", "meaning": "spring", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/haru-spring"},
    {"kanji": "夏", "word": "夏", "reading": "なつ", "meaning": "summer", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/natsu-summer"},
    {"kanji": "秋", "word": "秋", "reading": "あき", "meaning": "autumn", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/aki-autumn"},
    {"kanji": "冬", "word": "冬", "reading": "ふゆ", "meaning": "winter", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/fuyu-winter"},
    {"kanji": "空", "word": "空", "reading": "そら", "meaning": "sky", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/sora"},
    {"kanji": "天", "word": "天気", "reading": "てんき", "meaning": "weather", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/tenki"},
    {"kanji": "風", "word": "風", "reading": "かぜ", "meaning": "wind", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/kaze-wind"},
    {"kanji": "台", "word": "台風", "reading": "たいふう", "meaning": "typhoon", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/dai-stand"},
    {"kanji": "雲", "word": "雲", "reading": "くも", "meaning": "cloud", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/kumo-cloud"},
    {"kanji": "雪", "word": "雪", "reading": "ゆき", "meaning": "snow", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/yuki-snow"},
    {"kanji": "晴", "word": "晴れ", "reading": "はれ", "meaning": "clear weather", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/hare-sunny"},
    {"kanji": "星", "word": "星", "reading": "ほし", "meaning": "star", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/hoshi-star"},
    {"kanji": "光", "word": "光", "reading": "ひかり", "meaning": "light", "category": "Weather", "source": "https://langoal.com/teaching-materials/kanji/hikari-light"},
    {"kanji": "地", "word": "地下鉄", "reading": "ちかてつ", "meaning": "subway", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/chi-ground"},
    {"kanji": "谷", "word": "谷", "reading": "たに", "meaning": "valley", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/tani-valley"},
    {"kanji": "自", "word": "自分", "reading": "じぶん", "meaning": "oneself", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/ji-oneself"},
    {"kanji": "然", "word": "自然", "reading": "しぜん", "meaning": "nature", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/zen-naturally"},
    {"kanji": "草", "word": "草", "reading": "くさ", "meaning": "grass", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/kusa"},
    {"kanji": "原", "word": "草原", "reading": "そうげん", "meaning": "grasslands", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/hara-field"},
    {"kanji": "海", "word": "海", "reading": "うみ", "meaning": "sea", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/umi-sea"},
    {"kanji": "湖", "word": "湖", "reading": "みずうみ", "meaning": "lake", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/mizuumi-lake"},
    {"kanji": "池", "word": "池", "reading": "いけ", "meaning": "pond", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/ike-pond"},
    {"kanji": "里", "word": "里", "reading": "さと", "meaning": "village", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/sato-village"},
    {"kanji": "野", "word": "野", "reading": "の", "meaning": "field", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/no-field"},
    {"kanji": "虫", "word": "虫", "reading": "むし", "meaning": "insect", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/mushi"},
    {"kanji": "羽", "word": "羽", "reading": "はね", "meaning": "feather", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/hane-feather"},
    {"kanji": "馬", "word": "馬", "reading": "うま", "meaning": "horse", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/uma-horse"},
    {"kanji": "鳴", "word": "鳴く", "reading": "なく", "meaning": "call (an animal)", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/naku-make-sound"},
    {"kanji": "毛", "word": "毛", "reading": "け", "meaning": "hair", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/ke-hair"},
    {"kanji": "糸", "word": "糸", "reading": "いと", "meaning": "thread", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/ito-thread"},
    {"kanji": "衣", "word": "衣服", "reading": "いふく", "meaning": "clothes", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/i-clothes"},
    {"kanji": "服", "word": "服", "reading": "ふく", "meaning": "clothes", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/fuku-clothes"},
    {"kanji": "洋", "word": "洋服", "reading": "ようふく", "meaning": "western-style clothes", "category": "Countryside & clothes", "source": "https://langoal.com/teaching-materials/kanji/you-western"},
    {"kanji": "料", "word": "食料", "reading": "しょくりょう", "meaning": "food", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/ryou-material"},
    {"kanji": "理", "word": "料理", "reading": "りょうり", "meaning": "cooking", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/ri-logic"},
    {"kanji": "飯", "word": "ご飯", "reading": "ごはん", "meaning": "cooked rice; meal", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/meshi-meal"},
    {"kanji": "麦", "word": "麦", "reading": "むぎ", "meaning": "wheat; barley", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/mugi-barley"},
    {"kanji": "油", "word": "油", "reading": "あぶら", "meaning": "oil", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/abura-oil"},
    {"kanji": "酒", "word": "お酒", "reading": "おさけ", "meaning": "alcohol", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/sake-alcohol"},
    {"kanji": "味", "word": "味", "reading": "あじ", "meaning": "taste", "category": "Cooking", "source": "https://langoal.com/teaching-materials/kanji/aji-taste"},
    {"kanji": "住", "word": "住む", "reading": "すむ", "meaning": "live", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/sumu-live"},
    {"kanji": "所", "word": "所", "reading": "ところ", "meaning": "place", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/tokoro-place"},
    {"kanji": "都", "word": "都", "reading": "みやこ", "meaning": "capital", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/miyako-capital"},
    {"kanji": "道", "word": "道", "reading": "みち", "meaning": "road", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/michi-road"},
    {"kanji": "府", "word": "京都府", "reading": "きょうとふ", "meaning": "Kyoto prefecture", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/fu-prefecture"},
    {"kanji": "県", "word": "県", "reading": "けん", "meaning": "prefecture", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/ken-prefecture"},
    {"kanji": "京", "word": "東京都", "reading": "とうきょうと", "meaning": "Tokyo metropolis", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/kyou-capital"},
    {"kanji": "市", "word": "市", "reading": "し", "meaning": "city", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/ichi-market"},
    {"kanji": "区", "word": "区", "reading": "く", "meaning": "ward", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/ku-district"},
    {"kanji": "村", "word": "村", "reading": "むら", "meaning": "village", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/mura"},
    {"kanji": "番", "word": "番号", "reading": "ばんごう", "meaning": "number", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/ban-number"},
    {"kanji": "号", "word": "信号", "reading": "しんごう", "meaning": "traffic lights", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/gou-number"},
    {"kanji": "国", "word": "国", "reading": "くに", "meaning": "country", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/kuni-country"},
    {"kanji": "紙", "word": "紙", "reading": "かみ", "meaning": "paper", "category": "Address", "source": "https://langoal.com/teaching-materials/kanji/kami-paper"},
    {"kanji": "店", "word": "店", "reading": "みせ", "meaning": "shop", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/mise-shop"},
    {"kanji": "客", "word": "客", "reading": "きゃく", "meaning": "customer; guest", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/kyaku-guest"},
    {"kanji": "売", "word": "売る", "reading": "うる", "meaning": "sell", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/uru-sell"},
    {"kanji": "品", "word": "品物", "reading": "しなもの", "meaning": "goods", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/shina-goods"},
    {"kanji": "薬", "word": "薬", "reading": "くすり", "meaning": "medicine", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/kusuri-medicine"},
    {"kanji": "待", "word": "待つ", "reading": "まつ", "meaning": "wait", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/matsu-wait"},
    {"kanji": "合", "word": "合う", "reading": "あう", "meaning": "fit; match", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/au-match"},
    {"kanji": "計", "word": "計る", "reading": "はかる", "meaning": "measure", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/hakaru-measure"},
    {"kanji": "辺", "word": "辺り", "reading": "あたり", "meaning": "vicinity", "category": "Shopping", "source": "https://langoal.com/teaching-materials/kanji/atari-around"},
    {"kanji": "交", "word": "交差点", "reading": "こうさてん", "meaning": "intersection", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/majiwaru-intersect"},
    {"kanji": "通", "word": "通る", "reading": "とおる", "meaning": "go through", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/tooru-pass"},
    {"kanji": "荷", "word": "荷物", "reading": "にもつ", "meaning": "luggage", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/ni-luggage"},
    {"kanji": "送", "word": "送る", "reading": "おくる", "meaning": "send", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/okuru-send"},
    {"kanji": "宅", "word": "お宅", "reading": "おたく", "meaning": "your house", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/taku-house"},
    {"kanji": "止", "word": "止まる", "reading": "とまる", "meaning": "stop", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/tomeru-stop"},
    {"kanji": "急", "word": "急ぐ", "reading": "いそぐ", "meaning": "hurry", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/isogu-hurry"},
    {"kanji": "特", "word": "特に", "reading": "とくに", "meaning": "especially", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/toku-special"},
    {"kanji": "鉄", "word": "鉄", "reading": "てつ", "meaning": "iron", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/tetsu-iron"},
    {"kanji": "船", "word": "船", "reading": "ふね", "meaning": "ship", "category": "Transport", "source": "https://langoal.com/teaching-materials/kanji/fune-ship"},
    {"kanji": "部", "word": "部屋", "reading": "へや", "meaning": "room", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/bu-part"},
    {"kanji": "屋", "word": "本屋", "reading": "ほんや", "meaning": "bookstore", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/ya-house"},
    {"kanji": "教", "word": "教える", "reading": "おしえる", "meaning": "teach", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/oshieru-teach"},
    {"kanji": "室", "word": "教室", "reading": "きょうしつ", "meaning": "classroom", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/shitsu-room"},
    {"kanji": "会", "word": "会う", "reading": "あう", "meaning": "meet", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/au-meet"},
    {"kanji": "社", "word": "会社", "reading": "かいしゃ", "meaning": "company", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/sha-company"},
    {"kanji": "駅", "word": "駅", "reading": "えき", "meaning": "station", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/eki-station"},
    {"kanji": "工", "word": "工場", "reading": "こうじょう", "meaning": "factory", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/kou-craft"},
    {"kanji": "場", "word": "場所", "reading": "ばしょ", "meaning": "location", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/ba-place"},
    {"kanji": "病", "word": "病気", "reading": "びょうき", "meaning": "illness", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/byou-sick"},
    {"kanji": "院", "word": "病院", "reading": "びょういん", "meaning": "hospital", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/in-institution"},
    {"kanji": "公", "word": "公園", "reading": "こうえん", "meaning": "park", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/kou-public"},
    {"kanji": "園", "word": "動物園", "reading": "どうぶつえん", "meaning": "zoo", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/en-park"},
    {"kanji": "図", "word": "地図", "reading": "ちず", "meaning": "map", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/zu-drawing"},
    {"kanji": "館", "word": "図書館", "reading": "としょかん", "meaning": "library", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/kan-building"},
    {"kanji": "映", "word": "映画", "reading": "えいが", "meaning": "movie", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/ei-reflection"},
    {"kanji": "画", "word": "映画館", "reading": "えいがかん", "meaning": "movie theater", "category": "Places", "source": "https://langoal.com/teaching-materials/kanji/ga-picture"},
    {"kanji": "勉", "word": "勉強", "reading": "べんきょう", "meaning": "study", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/ben-study"},
    {"kanji": "強", "word": "強い", "reading": "つよい", "meaning": "strong", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/tsuyoi-strong"},
    {"kanji": "宿", "word": "宿題", "reading": "しゅくだい", "meaning": "homework", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/yado-lodging"},
    {"kanji": "題", "word": "問題", "reading": "もんだい", "meaning": "problem", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/dai-title"},
    {"kanji": "質", "word": "質", "reading": "しつ", "meaning": "quality", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/shitsu-quality"},
    {"kanji": "問", "word": "質問", "reading": "しつもん", "meaning": "question", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/toi-question"},
    {"kanji": "試", "word": "試合", "reading": "しあい", "meaning": "match", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/tamesu-try"},
    {"kanji": "験", "word": "試験", "reading": "しけん", "meaning": "examination", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/ken-testing"},
    {"kanji": "答", "word": "答え", "reading": "こたえ", "meaning": "answer", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/kotae-answer"},
    {"kanji": "考", "word": "考える", "reading": "かんがえる", "meaning": "consider", "category": "Study", "source": "https://langoal.com/teaching-materials/kanji/kangaeru-consider"},
    {"kanji": "字", "word": "字", "reading": "じ", "meaning": "character", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/ji"},
    {"kanji": "文", "word": "文", "reading": "ぶん", "meaning": "sentence", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/bun"},
    {"kanji": "漢", "word": "漢字", "reading": "かんじ", "meaning": "kanji", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/kan-china"},
    {"kanji": "数", "word": "数", "reading": "かず", "meaning": "number", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/kazu-number"},
    {"kanji": "英", "word": "英語", "reading": "えいご", "meaning": "English", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/ei-english"},
    {"kanji": "語", "word": "日本語", "reading": "にほんご", "meaning": "Japanese", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/go-language"},
    {"kanji": "化", "word": "文化", "reading": "ぶんか", "meaning": "culture", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/bakeru-change"},
    {"kanji": "育", "word": "育つ", "reading": "そだつ", "meaning": "grow up", "category": "Subjects", "source": "https://langoal.com/teaching-materials/kanji/sodatsu-grow"},
    {"kanji": "研", "word": "研究", "reading": "けんきゅう", "meaning": "research", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/togu-polish"},
    {"kanji": "究", "word": "研究室", "reading": "けんきゅうしつ", "meaning": "laboratory", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/kyuu-research"},
    {"kanji": "医", "word": "医者", "reading": "いしゃ", "meaning": "doctor", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/i-doctor"},
    {"kanji": "科", "word": "科学", "reading": "かがく", "meaning": "science", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/ka-department"},
    {"kanji": "政", "word": "政治", "reading": "せいじ", "meaning": "politics", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/sei-politics"},
    {"kanji": "治", "word": "治める", "reading": "おさめる", "meaning": "govern", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/osameru-govern"},
    {"kanji": "経", "word": "経験", "reading": "けいけん", "meaning": "experience", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/kei-passthrough"},
    {"kanji": "済", "word": "経済", "reading": "けいざい", "meaning": "economy", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/sumu-finish"},
    {"kanji": "歴", "word": "学歴", "reading": "がくれき", "meaning": "academic background", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/reki-history"},
    {"kanji": "史", "word": "歴史", "reading": "れきし", "meaning": "history", "category": "University", "source": "https://langoal.com/teaching-materials/kanji/shi-history"},
    {"kanji": "運", "word": "運ぶ", "reading": "はこぶ", "meaning": "carry", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/hakobu-carry"},
    {"kanji": "動", "word": "動く", "reading": "うごく", "meaning": "move", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/ugoku-move"},
    {"kanji": "泳", "word": "泳ぐ", "reading": "およぐ", "meaning": "swim", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/oyogu-swim"},
    {"kanji": "旅", "word": "旅", "reading": "たび", "meaning": "travel", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/tabi-trip"},
    {"kanji": "世", "word": "世界", "reading": "せかい", "meaning": "world", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/yo-world"},
    {"kanji": "界", "word": "限界", "reading": "げんかい", "meaning": "limit", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/kai-world"},
    {"kanji": "練", "word": "練習", "reading": "れんしゅう", "meaning": "practice", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/ren-practice"},
    {"kanji": "習", "word": "習う", "reading": "ならう", "meaning": "learn", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/narau-learn"},
    {"kanji": "写", "word": "写真", "reading": "しゃしん", "meaning": "photograph", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/utsusu-copy"},
    {"kanji": "真", "word": "真ん中", "reading": "まんなか", "meaning": "middle", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/makoto-real"},
    {"kanji": "楽", "word": "楽しい", "reading": "たのしい", "meaning": "fun", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/tanoshii-fun"},
    {"kanji": "声", "word": "声", "reading": "こえ", "meaning": "voice", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/koe-voice"},
    {"kanji": "歌", "word": "歌", "reading": "うた", "meaning": "song", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/uta-song"},
    {"kanji": "集", "word": "集める", "reading": "あつめる", "meaning": "collect", "category": "Hobbies", "source": "https://langoal.com/teaching-materials/kanji/atsumeru-collect"},
    {"kanji": "作", "word": "作る", "reading": "つくる", "meaning": "make", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/tsukuru-make"},
    {"kanji": "使", "word": "使う", "reading": "つかう", "meaning": "use", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/tsukau-use"},
    {"kanji": "思", "word": "思う", "reading": "おもう", "meaning": "think", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/omou-think"},
    {"kanji": "持", "word": "持つ", "reading": "もつ", "meaning": "hold", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/motsu-hold"},
    {"kanji": "当", "word": "当たる", "reading": "あたる", "meaning": "hit; be correct", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/ataru-hit"},
    {"kanji": "知", "word": "知る", "reading": "しる", "meaning": "know", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/shiru-know"},
    {"kanji": "働", "word": "働く", "reading": "はたらく", "meaning": "work", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/hataraku-work"},
    {"kanji": "始", "word": "始まる", "reading": "はじまる", "meaning": "begin", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/hajimaru-begin"},
    {"kanji": "終", "word": "終わる", "reading": "おわる", "meaning": "finish", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/owaru-finish"},
    {"kanji": "乗", "word": "乗る", "reading": "のる", "meaning": "get on; ride", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/noru-ride"},
    {"kanji": "降", "word": "降りる", "reading": "おりる", "meaning": "get off", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/oriru-getoff"},
    {"kanji": "開", "word": "開ける", "reading": "あける", "meaning": "open", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/akeru-open"},
    {"kanji": "閉", "word": "閉める", "reading": "しめる", "meaning": "close", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/shimeru-close"},
    {"kanji": "発", "word": "出発", "reading": "しゅっぱつ", "meaning": "departure", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/hatsu-departure"},
    {"kanji": "着", "word": "着く", "reading": "つく", "meaning": "arrive at", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/tsuku-arrive"},
    {"kanji": "走", "word": "走る", "reading": "はしる", "meaning": "run", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/hashiru-run"},
    {"kanji": "歩", "word": "歩く", "reading": "あるく", "meaning": "walk", "category": "Paired verbs", "source": "https://langoal.com/teaching-materials/kanji/aruku-walk"},
    {"kanji": "近", "word": "近い", "reading": "ちかい", "meaning": "near", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/chikai-near"},
    {"kanji": "遠", "word": "遠い", "reading": "とおい", "meaning": "far", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/tooi-far"},
    {"kanji": "重", "word": "重い", "reading": "おもい", "meaning": "heavy", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/omoi-heavy"},
    {"kanji": "軽", "word": "軽い", "reading": "かるい", "meaning": "light", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/karui-light"},
    {"kanji": "早", "word": "早い", "reading": "はやい", "meaning": "early", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/hayai-early"},
    {"kanji": "速", "word": "速い", "reading": "はやい", "meaning": "fast", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/hayai-fast"},
    {"kanji": "遅", "word": "遅い", "reading": "おそい", "meaning": "late; slow", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/osoi-late"},
    {"kanji": "広", "word": "広い", "reading": "ひろい", "meaning": "spacious", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/hiroi-wide"},
    {"kanji": "細", "word": "細い", "reading": "ほそい", "meaning": "thin", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/hosoi-thin"},
    {"kanji": "太", "word": "太い", "reading": "ふとい", "meaning": "thick", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/hutoi-thick"},
    {"kanji": "暑", "word": "暑い", "reading": "あつい", "meaning": "hot", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/atsui-hot"},
    {"kanji": "寒", "word": "寒い", "reading": "さむい", "meaning": "cold", "category": "Adjectives 1", "source": "https://langoal.com/teaching-materials/kanji/samui-cold"},
    {"kanji": "低", "word": "低い", "reading": "ひくい", "meaning": "low", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/hikui-low"},
    {"kanji": "短", "word": "短い", "reading": "みじかい", "meaning": "short", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/mijikai-short"},
    {"kanji": "弱", "word": "弱い", "reading": "よわい", "meaning": "weak", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/yowai-weak"},
    {"kanji": "若", "word": "若い", "reading": "わかい", "meaning": "young", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/wakai-young"},
    {"kanji": "静", "word": "静か", "reading": "しずか", "meaning": "quiet", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/shizuka-quiet"},
    {"kanji": "有", "word": "有名", "reading": "ゆうめい", "meaning": "famous", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/aru-have"},
    {"kanji": "心", "word": "心", "reading": "こころ", "meaning": "heart", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/kokoro-heart"},
    {"kanji": "同", "word": "同じ", "reading": "おなじ", "meaning": "same", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/onaji-same"},
    {"kanji": "便", "word": "便利", "reading": "べんり", "meaning": "convenient", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/ben-convenience"},
    {"kanji": "利", "word": "利用", "reading": "りよう", "meaning": "use", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/ri-profit"},
    {"kanji": "親", "word": "親", "reading": "おや", "meaning": "parent", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/oya-parent"},
    {"kanji": "切", "word": "切る", "reading": "きる", "meaning": "cut", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/kiru-cut"},
    {"kanji": "不", "word": "不便", "reading": "ふべん", "meaning": "inconvenient", "category": "Adjectives 2", "source": "https://langoal.com/teaching-materials/kanji/fu-non"},
  ],
};
