// Kanji membership and example word/readings checked against Langoal on 2026-10-05.
// One example per kanji; this is not an exhaustive reading list.
// Numbers 1–10 use standalone readings, checked against the Japan Foundation on 2026-10-08.
export const n5 = {
  id: 'n5',
  label: 'JLPT N5',
  source: 'https://langoal.com/teaching-materials/kanji/n5-overview.html',
  verifiedOn: '2026-10-05',
  cards: [
    {"kanji": "一", "word": "一", "reading": "いち", "meaning": "one", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/ichi"},
    {"kanji": "二", "word": "二", "reading": "に", "meaning": "two", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/ni"},
    {"kanji": "三", "word": "三", "reading": "さん", "meaning": "three", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/san"},
    {"kanji": "四", "word": "四", "reading": "よん", "meaning": "four", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/yon"},
    {"kanji": "五", "word": "五", "reading": "ご", "meaning": "five", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/go"},
    {"kanji": "六", "word": "六", "reading": "ろく", "meaning": "six", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/roku"},
    {"kanji": "七", "word": "七", "reading": "なな", "meaning": "seven", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/nana"},
    {"kanji": "八", "word": "八", "reading": "はち", "meaning": "eight", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/hachi"},
    {"kanji": "九", "word": "九", "reading": "きゅう", "meaning": "nine", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/kyuu"},
    {"kanji": "十", "word": "十", "reading": "じゅう", "meaning": "ten", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/juu"},
    {"kanji": "百", "word": "百", "reading": "ひゃく", "meaning": "hundred", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/hyaku"},
    {"kanji": "千", "word": "千", "reading": "せん", "meaning": "thousand", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/sen"},
    {"kanji": "円", "word": "十円", "reading": "じゅうえん", "meaning": "10 yen", "category": "Numbers", "source": "https://langoal.com/teaching-materials/kanji/en"},
    {"kanji": "月", "word": "月曜日", "reading": "げつようび", "meaning": "monday", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/getsuyoubi"},
    {"kanji": "火", "word": "火曜日", "reading": "かようび", "meaning": "tuesday", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/kayoubi"},
    {"kanji": "水", "word": "水", "reading": "みず", "meaning": "water", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/suiyoubi"},
    {"kanji": "木", "word": "木", "reading": "き", "meaning": "tree", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/mokuyoubi"},
    {"kanji": "金", "word": "お金", "reading": "おかね", "meaning": "money", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/kinyoubi"},
    {"kanji": "土", "word": "土", "reading": "つち", "meaning": "soil", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/doyoubi"},
    {"kanji": "日", "word": "日", "reading": "ひ", "meaning": "sun", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/nichiyoubi"},
    {"kanji": "年", "word": "一年", "reading": "いちねん", "meaning": "one year", "category": "Calendar", "source": "https://langoal.com/teaching-materials/kanji/nen"},
    {"kanji": "人", "word": "人", "reading": "ひと", "meaning": "person", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/hito"},
    {"kanji": "子", "word": "子ども", "reading": "こども", "meaning": "child", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/kodomo"},
    {"kanji": "男", "word": "男", "reading": "おとこ", "meaning": "man", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/otoko"},
    {"kanji": "女", "word": "女", "reading": "おんな", "meaning": "woman", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/onna"},
    {"kanji": "父", "word": "お父さん", "reading": "おとうさん", "meaning": "father", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/otousan"},
    {"kanji": "母", "word": "お母さん", "reading": "おかあさん", "meaning": "mother", "category": "People", "source": "https://langoal.com/teaching-materials/kanji/okaasan"},
    {"kanji": "口", "word": "口", "reading": "くち", "meaning": "mouth", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/kuchi"},
    {"kanji": "目", "word": "目", "reading": "め", "meaning": "eye", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/me"},
    {"kanji": "耳", "word": "耳", "reading": "みみ", "meaning": "ear", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/mimi"},
    {"kanji": "手", "word": "手", "reading": "て", "meaning": "hand", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/te"},
    {"kanji": "足", "word": "足", "reading": "あし", "meaning": "foot, leg", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/ashi"},
    {"kanji": "体", "word": "体", "reading": "からだ", "meaning": "body", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/karada"},
    {"kanji": "力", "word": "力", "reading": "ちから", "meaning": "power, strength", "category": "Body", "source": "https://langoal.com/teaching-materials/kanji/chikara"},
    {"kanji": "上", "word": "上", "reading": "うえ", "meaning": "above; on top", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/ue"},
    {"kanji": "下", "word": "下", "reading": "した", "meaning": "below; down", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/shita"},
    {"kanji": "左", "word": "左", "reading": "ひだり", "meaning": "left", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/hidari"},
    {"kanji": "右", "word": "右", "reading": "みぎ", "meaning": "right", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/migi"},
    {"kanji": "大", "word": "大きい", "reading": "おおきい", "meaning": "big", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/ookii"},
    {"kanji": "小", "word": "小さい", "reading": "ちいさい", "meaning": "small", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/chiisai"},
    {"kanji": "中", "word": "中", "reading": "なか", "meaning": "middle", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/naka"},
    {"kanji": "外", "word": "外", "reading": "そと", "meaning": "outside", "category": "Position", "source": "https://langoal.com/teaching-materials/kanji/soto"},
    {"kanji": "学", "word": "学生", "reading": "がくせい", "meaning": "student", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/manabu"},
    {"kanji": "校", "word": "学校", "reading": "がっこう", "meaning": "school", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/gakkou"},
    {"kanji": "先", "word": "先生", "reading": "せんせい", "meaning": "teacher", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/saki"},
    {"kanji": "生", "word": "生きる", "reading": "いきる", "meaning": "live", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/ikiru"},
    {"kanji": "本", "word": "本", "reading": "ほん", "meaning": "book", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/hon"},
    {"kanji": "名", "word": "名前", "reading": "なまえ", "meaning": "name", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/namae"},
    {"kanji": "友", "word": "友達", "reading": "ともだち", "meaning": "friend", "category": "School", "source": "https://langoal.com/teaching-materials/kanji/tomodachi"},
    {"kanji": "山", "word": "山", "reading": "やま", "meaning": "mountain", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/yama"},
    {"kanji": "川", "word": "川", "reading": "かわ", "meaning": "river", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/kawa"},
    {"kanji": "田", "word": "田", "reading": "た", "meaning": "rice field", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/tanbo"},
    {"kanji": "石", "word": "石", "reading": "いし", "meaning": "stone", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/ishi"},
    {"kanji": "雨", "word": "雨", "reading": "あめ", "meaning": "rain", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/ame"},
    {"kanji": "夕", "word": "夕方", "reading": "ゆうがた", "meaning": "evening", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/yuugata"},
    {"kanji": "岩", "word": "岩", "reading": "いわ", "meaning": "rock", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/iwa"},
    {"kanji": "音", "word": "音", "reading": "おと", "meaning": "sound, note", "category": "Nature", "source": "https://langoal.com/teaching-materials/kanji/oto"},
    {"kanji": "林", "word": "林", "reading": "はやし", "meaning": "woods", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/hayashi"},
    {"kanji": "森", "word": "森", "reading": "もり", "meaning": "forest", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/mori"},
    {"kanji": "花", "word": "花", "reading": "はな", "meaning": "flower", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/hana"},
    {"kanji": "竹", "word": "竹", "reading": "たけ", "meaning": "bamboo", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/take"},
    {"kanji": "犬", "word": "犬", "reading": "いぬ", "meaning": "dog", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/inu"},
    {"kanji": "貝", "word": "貝", "reading": "かい", "meaning": "shell; shellfish", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/kai"},
    {"kanji": "牛", "word": "牛", "reading": "うし", "meaning": "cow", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/ushi"},
    {"kanji": "魚", "word": "魚", "reading": "さかな", "meaning": "fish", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/sakana"},
    {"kanji": "鳥", "word": "鳥", "reading": "とり", "meaning": "bird", "category": "Plants & animals", "source": "https://langoal.com/teaching-materials/kanji/tori"},
    {"kanji": "米", "word": "お米", "reading": "おこめ", "meaning": "uncooked rice", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/kome"},
    {"kanji": "肉", "word": "肉", "reading": "にく", "meaning": "meat", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/niku"},
    {"kanji": "茶", "word": "お茶", "reading": "おちゃ", "meaning": "green tea", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/ocha"},
    {"kanji": "好", "word": "好き", "reading": "すき", "meaning": "like; fond of", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/suki"},
    {"kanji": "物", "word": "物", "reading": "もの", "meaning": "thing", "category": "Food", "source": "https://langoal.com/teaching-materials/kanji/mono"},
    {"kanji": "今", "word": "今", "reading": "いま", "meaning": "now", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/ima"},
    {"kanji": "何", "word": "何", "reading": "なに", "meaning": "what", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/nani"},
    {"kanji": "分", "word": "分かる", "reading": "わかる", "meaning": "understand", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/wakaru"},
    {"kanji": "半", "word": "半", "reading": "はん", "meaning": "half", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/hanbun"},
    {"kanji": "方", "word": "方", "reading": "かた", "meaning": "person (polite)", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/kata-howto"},
    {"kanji": "時", "word": "時", "reading": "とき", "meaning": "time", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/toki"},
    {"kanji": "間", "word": "時間", "reading": "じかん", "meaning": "time", "category": "Time", "source": "https://langoal.com/teaching-materials/kanji/aida"},
    {"kanji": "町", "word": "町", "reading": "まち", "meaning": "town, city", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/machi"},
    {"kanji": "寺", "word": "寺", "reading": "てら", "meaning": "Buddhist temple", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/tera"},
    {"kanji": "東", "word": "東", "reading": "ひがし", "meaning": "east", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/higashi"},
    {"kanji": "西", "word": "西", "reading": "にし", "meaning": "west", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/nishi"},
    {"kanji": "南", "word": "南", "reading": "みなみ", "meaning": "south", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/minami"},
    {"kanji": "北", "word": "北", "reading": "きた", "meaning": "north", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/kita"},
    {"kanji": "車", "word": "車", "reading": "くるま", "meaning": "car", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/kuruma"},
    {"kanji": "電", "word": "電気", "reading": "でんき", "meaning": "electricity", "category": "City", "source": "https://langoal.com/teaching-materials/kanji/denki"},
    {"kanji": "高", "word": "高い", "reading": "たかい", "meaning": "tall, expensive", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/takai"},
    {"kanji": "安", "word": "安い", "reading": "やすい", "meaning": "cheap", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/yasui"},
    {"kanji": "多", "word": "多い", "reading": "おおい", "meaning": "many", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/ooi"},
    {"kanji": "少", "word": "少ない", "reading": "すくない", "meaning": "few; not many", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/sukunai"},
    {"kanji": "新", "word": "新しい", "reading": "あたらしい", "meaning": "new", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/atarashii"},
    {"kanji": "古", "word": "古い", "reading": "ふるい", "meaning": "old", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/furui"},
    {"kanji": "明", "word": "明るい", "reading": "あかるい", "meaning": "bright", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/akarui"},
    {"kanji": "暗", "word": "暗い", "reading": "くらい", "meaning": "dark", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/kurai"},
    {"kanji": "長", "word": "長い", "reading": "ながい", "meaning": "long", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/nagai"},
    {"kanji": "元", "word": "元気", "reading": "げんき", "meaning": "healthy; energetic", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/moto"},
    {"kanji": "気", "word": "天気", "reading": "てんき", "meaning": "weather", "category": "Adjectives", "source": "https://langoal.com/teaching-materials/kanji/genki"},
    {"kanji": "見", "word": "見る", "reading": "みる", "meaning": "see, watch", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/miru"},
    {"kanji": "立", "word": "立つ", "reading": "たつ", "meaning": "stand", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/tatsu"},
    {"kanji": "入", "word": "入る", "reading": "はいる", "meaning": "enter", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/hairu"},
    {"kanji": "出", "word": "出る", "reading": "でる", "meaning": "leave; go out", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/deru"},
    {"kanji": "休", "word": "休む", "reading": "やすむ", "meaning": "rest", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/yasumu"},
    {"kanji": "行", "word": "行く", "reading": "いく", "meaning": "go", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/iku"},
    {"kanji": "来", "word": "来る", "reading": "くる", "meaning": "come", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kuru"},
    {"kanji": "言", "word": "言う", "reading": "いう", "meaning": "say", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/iu"},
    {"kanji": "帰", "word": "帰る", "reading": "かえる", "meaning": "go home", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kaeru"},
    {"kanji": "書", "word": "書く", "reading": "かく", "meaning": "write", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kaku"},
    {"kanji": "読", "word": "読む", "reading": "よむ", "meaning": "read", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/yomu"},
    {"kanji": "話", "word": "話す", "reading": "はなす", "meaning": "speak", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/hanasu"},
    {"kanji": "聞", "word": "聞く", "reading": "きく", "meaning": "hear, listen, ask", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kiku"},
    {"kanji": "食", "word": "食べる", "reading": "たべる", "meaning": "eat", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/taberu"},
    {"kanji": "飲", "word": "飲む", "reading": "のむ", "meaning": "drink", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/nomu"},
    {"kanji": "買", "word": "買う", "reading": "かう", "meaning": "buy", "category": "Verbs", "source": "https://langoal.com/teaching-materials/kanji/kau"},
  ],
};
